### ISSUE TITLE
serious error

### ISSUE THREAD

**Issue by friedrichyuan** [facebookresearch/impact-driven-exploration#14]
Traceback (most recent call last):
  File "/220019034/anaconda3/envs/torch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/220019034/anaconda3/envs/torch/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/220019034/code/impact-driven-exploration/src/algos/ride.py", line 317, in batch_and_learn
    stats = learn(model, learner_model, state_embedding_model, forward_dynamics_model, 
  File "/220019034/code/impact-driven-exploration/src/algos/ride.py", line 92, in learn
    learner_outputs, unused_state = model(batch, initial_agent_state)
  File "/220019034/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/220019034/code/impact-driven-exploration/src/models.py", line 339, in forward
    action = torch.multinomial(
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
[INFO:57 ride:381 2021-07-09 05:55:38,284] After 0 frames: loss inf @ 0.0 fps. Stats:
{}

**Comment by friedrichyuan** [comment]
With all my respect, I think you guys haven't checked your codes before publishing it.

**Comment by linhao1998** [comment]
I have the same error.

**Comment by jayelm** [comment]
This is likely a python/torch version issue - following the setup instructions in the README fixed things for me.

**Comment by CrazySssst** [comment]
I solve this problem by changing dtype of done from torch.uint8 to torch.bool which you can find in the function create_buffers of src/utils.py

`done=dict(size=(T+1), dtype=torch.uint8)  -> done=dict(size=(T+1), dtype=torch.bool)`

**Comment by egg-west** [comment]
> I solve this problem by changing dtype of done from torch.uint8 to torch.bool which you can find in the function create_buffers of src/utils.py
> 
> `done=dict(size=(T+1), dtype=torch.uint8) -> done=dict(size=(T+1), dtype=torch.bool)`

Works for me (Windows 10) after I get the same error after I tried to make all package versions the same.
